"""new things

Revision ID: 3925cb73a63a
Revises: 05a18c8956c1
Create Date: 2021-05-27 17:43:18.138671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '3925cb73a63a'
down_revision = '05a18c8956c1'
branch_labels = None
depends_on = None


def upgrade():
    dispersion_param = ENUM('STANDARD_DEVIATION', 'CONFIDENCE_INTERVAL_95', 'STANDARD_ERROR', 'FULL_RANGE', 'GEOMETRIC_COEFFICIENT_OF_VARIATION', 'INTER_QUARTILE_RANGE', 'CONFIDENCE_INTERVAL_90', 'CONFIDENCE_INTERVAL_80', 'CONFIDENCE_INTERVAL_97', 'CONFIDENCE_INTERVAL_99', 'CONFIDENCE_INTERVAL_60', 'CONFIDENCE_INTERVAL_96', 'CONFIDENCE_INTERVAL_98', 'CONFIDENCE_INTERVAL_70', 'CONFIDENCE_INTERVAL_85', 'CONFIDENCE_INTERVAL_75', 'CONFIDENCE_INTERVAL_94', 'CONFIDENCE_INTERVAL_100', 'NA', name='dispersion_param')
    dispersion_param.create(op.get_bind())
    op.add_column('measures', sa.Column('dispersion', dispersion_param, nullable=True))
    measure_param = ENUM('MEAN', 'NUMBER', 'COUNT_OF_PARTICIPANTS', 'LEAST_SQUARES_MEAN', 'GEOMETRIC_MEAN', 'COUNT_OF_UNITS', 'GEOMETRIC_LEAST_SQUARES_MEAN', 'LOG_MEAN', 'NA', name='measure_param')
    measure_param.create(op.get_bind())
    op.add_column('measures', sa.Column('param', measure_param, nullable=True))
    op.add_column('measures', sa.Column('units', sa.String(length=40), nullable=True))
    op.add_column('studies', sa.Column('short_title', sa.String(length=300), nullable=True))
    op.add_column('studies', sa.Column('official_title', sa.String(length=600), nullable=True))
    op.add_column('studies', sa.Column('sponser', sa.String(length=160), nullable=True))
    op.drop_column('studies', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('studies', 'sponser')
    op.drop_column('studies', 'official_title')
    op.drop_column('studies', 'short_title')
    op.drop_column('measures', 'units')
    op.drop_column('measures', 'param')
    op.drop_column('measures', 'dispersion')
    # ### end Alembic commands ###
