"""upate groups

Revision ID: 3d09c4f5a25a
Revises: 925312989b1d
Create Date: 2021-06-08 06:53:33.412866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d09c4f5a25a'
down_revision = '925312989b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baselines', sa.Column('group', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'baselines', 'groups', ['group'], ['id'])
    op.add_column('groups', sa.Column('study_id', sa.String(length=7), nullable=True))
    op.add_column('groups', sa.Column('study', sa.String(length=11), nullable=True))
    op.create_foreign_key(None, 'groups', 'studies', ['study'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'study')
    op.drop_column('groups', 'study_id')
    op.drop_constraint(None, 'baselines', type_='foreignkey')
    op.drop_column('baselines', 'group')
    # ### end Alembic commands ###
