"""links studies and baselines

Revision ID: 925312989b1d
Revises: ee246b0799c5
Create Date: 2021-06-08 06:44:29.380916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925312989b1d'
down_revision = 'ee246b0799c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baselines', sa.Column('study', sa.String(length=11), nullable=True))
    op.create_foreign_key(None, 'baselines', 'studies', ['study'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'baselines', type_='foreignkey')
    op.drop_column('baselines', 'study')
    # ### end Alembic commands ###
