"""add treatment brand name

Revision ID: b2edc4f164ee
Revises: 5201b1561ec1
Create Date: 2022-10-13 16:31:23.948780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2edc4f164ee'
down_revision = '5201b1561ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_brand_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['treatment'], ['treatments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('effect_groups')
    op.drop_index('administrations_group_ind', table_name='administrations')
    op.create_foreign_key(None, 'administrations', 'groups', ['group'], ['id'])
    op.create_foreign_key(None, 'administrations', 'treatments', ['treatment'], ['id'])
    op.drop_index('analytics_measure_ind', table_name='analytics')
    op.create_foreign_key(None, 'analytics', 'measures', ['measure'], ['id'])
    op.create_foreign_key(None, 'analytics', 'studies', ['study'], ['id'])
    op.create_foreign_key(None, 'baselines', 'studies', ['study'], ['id'])
    op.drop_index('comparison_analytics_ind', table_name='comparison')
    op.create_foreign_key(None, 'comparison', 'groups', ['group'], ['id'])
    op.create_foreign_key(None, 'comparison', 'analytics', ['analytic'], ['id'])
    op.create_foreign_key(None, 'conditionscores', 'conditions', ['condition'], ['id'])
    op.create_foreign_key(None, 'conditionscores', 'treatments', ['treatment'], ['id'])
    op.create_foreign_key(None, 'criteria', 'studies', ['study'], ['id'])
    op.drop_index('effects_group_ind', table_name='effects')
    op.drop_index('effects_study_ind', table_name='effects')
    op.create_foreign_key(None, 'effects', 'effectsgroups', ['group'], ['id'])
    op.create_foreign_key(None, 'effects', 'studies', ['study'], ['id'])
    op.create_foreign_key(None, 'effectsadministrations', 'treatments', ['treatment'], ['id'])
    op.create_foreign_key(None, 'effectsadministrations', 'effectsgroups', ['group'], ['id'])
    op.drop_index('effectsgroups_study_ind', table_name='effectsgroups')
    op.create_foreign_key(None, 'groups', 'studies', ['study'], ['id'])
    op.create_foreign_key(None, 'measures', 'studies', ['study'], ['id'])
    op.drop_index('outcomes_measures_ind', table_name='outcomes')
    op.create_foreign_key(None, 'outcomes', 'groups', ['group'], ['id'])
    op.create_foreign_key(None, 'outcomes', 'measures', ['measure'], ['id'])
    op.create_foreign_key(None, 'outcomes', 'studies', ['study'], ['id'])
    op.drop_index('study_conditions_study_ind', table_name='study_conditions')
    op.create_foreign_key(None, 'study_conditions', 'studies', ['study'], ['id'])
    op.create_foreign_key(None, 'study_conditions', 'conditions', ['condition'], ['id'])
    op.drop_index('study_treatments_study_ind', table_name='study_treatments')
    op.create_foreign_key(None, 'study_treatments', 'treatments', ['treatment'], ['id'])
    op.create_foreign_key(None, 'study_treatments', 'studies', ['study'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_treatments', type_='foreignkey')
    op.drop_constraint(None, 'study_treatments', type_='foreignkey')
    op.create_index('study_treatments_study_ind', 'study_treatments', ['study'], unique=False)
    op.drop_constraint(None, 'study_conditions', type_='foreignkey')
    op.drop_constraint(None, 'study_conditions', type_='foreignkey')
    op.create_index('study_conditions_study_ind', 'study_conditions', ['study'], unique=False)
    op.drop_constraint(None, 'outcomes', type_='foreignkey')
    op.drop_constraint(None, 'outcomes', type_='foreignkey')
    op.drop_constraint(None, 'outcomes', type_='foreignkey')
    op.create_index('outcomes_measures_ind', 'outcomes', ['measure'], unique=False)
    op.drop_constraint(None, 'measures', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_index('effectsgroups_study_ind', 'effectsgroups', ['study'], unique=False)
    op.drop_constraint(None, 'effectsadministrations', type_='foreignkey')
    op.drop_constraint(None, 'effectsadministrations', type_='foreignkey')
    op.drop_constraint(None, 'effects', type_='foreignkey')
    op.drop_constraint(None, 'effects', type_='foreignkey')
    op.create_index('effects_study_ind', 'effects', ['study'], unique=False)
    op.create_index('effects_group_ind', 'effects', ['group'], unique=False)
    op.drop_constraint(None, 'criteria', type_='foreignkey')
    op.drop_constraint(None, 'conditionscores', type_='foreignkey')
    op.drop_constraint(None, 'conditionscores', type_='foreignkey')
    op.drop_constraint(None, 'comparison', type_='foreignkey')
    op.drop_constraint(None, 'comparison', type_='foreignkey')
    op.create_index('comparison_analytics_ind', 'comparison', ['analytic'], unique=False)
    op.drop_constraint(None, 'baselines', type_='foreignkey')
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.create_index('analytics_measure_ind', 'analytics', ['measure'], unique=False)
    op.drop_constraint(None, 'administrations', type_='foreignkey')
    op.drop_constraint(None, 'administrations', type_='foreignkey')
    op.create_index('administrations_group_ind', 'administrations', ['group'], unique=False)
    op.create_table('effect_groups',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('study', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('study_id', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('treatment_brand_names')
    # ### end Alembic commands ###
