"""no_studies to treats

Revision ID: cda171c05194
Revises: 5063cd84cb56
Create Date: 2021-06-25 06:42:44.876671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda171c05194'
down_revision = '5063cd84cb56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('no_studies', sa.Integer(), nullable=True))
    op.drop_constraint('treatments_company_fkey', 'treatments', type_='foreignkey')
    op.drop_column('treatments', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatments', sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('treatments_company_fkey', 'treatments', 'companies', ['company'], ['id'])
    op.drop_column('treatments', 'no_studies')
    # ### end Alembic commands ###
